### ISSUE TITLE
How to set the sample order for the "sequence_per_sample.py"

### ISSUE THREAD

**Issue by ld9866** [WarrenLab/chicken-pangenome-paper#2]
Dear authors:
With your help, we have successfully executed sequence_per_sample.py in our data, but the order does not align with our idea. 
I want to ask if there is any way to set the order of samples in this script.
Best day

**Comment by esrice** [comment]
No, the whole point of this script is that it orders the samples by how much new sequence they add to the graph. You can choose the first one with the `-f` flag if you consider the "reference" to be a different sequence than the most complete one, but after that all samples are necessarily ordered by their novel contribution to the graph.
